### ISSUE TITLE
为什么我的github 库不能作为依赖呢

### ISSUE THREAD

**Issue by zongxiaomi** [seeways/AndroidUtils#1]
依赖会报错，提示Failed Resolve the com.github.XXX:xxx:1.0

**Comment by zongxiaomi** [comment]
以及发现这个问题的所在了，jitpack服务器会有延时，所以要等5分钟之后再Sync

**Comment by seeways** [comment]
对，而且我忘了吧.idea忽略了，等下做

**Comment by zongxiaomi** [comment]
一年了哥哥  测一年都发生了什么
